stages:
  train:
    cmd: python src/train.py --schema "config/schema.json" --params "config/params.yaml"
    deps:
      - src/train.py
      - src/data_loader.py
      - config/params.yaml
      - config/schema.json
      - data/telecom_churn/raw/telecom_churn.csv
    params:
      - config/params.yaml:
          - data
          - model
    outs:
      - data/telecom_churn/processed
      - artifacts/model.pkl
      - artifacts/transformations.pkl

  validate:
    cmd: python src/validate.py  --params "config/params.yaml"
    deps:
      - src/validate.py
      - src/data_loader.py
      - config/params.yaml
      - data/telecom_churn/processed
      - artifacts/model.pkl
    
    params:
      - config/params.yaml:
          - validation_data
          - reports
    metrics:
      - reports/metrics.json:
          cache: false
    outs:
      - reports/metrics.md:
          cache: false
      - reports/metrics_comparison.json:
          cache: false